spring:
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/bushub_discovery
    username: root
    password: adminadmin

eureka:
  client:
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.17.0.1:9001/eureka


demo:
  message: Hello From DEV!
